services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - 80:9000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./mealie/:/app/data
  mealie_scraper:
    build:
      dockerfile: ./Dockerfile
    container_name: mealie_scraper
    restart: unless-stopped
    depends_on:
      - "mealie"
    secrets:
      - api_token
      - proxy
    environment:
      # When setting API path, be sure to use container-side port not host-side
      - API_PATH=http://mealie:9000/api
      - PROXY_ENABLE=true
      - SEARCH_SITES=https://www.simplyrecipes.com/
      - ALLOWED_DOMAINS=www.simplyrecipes.com
      - LOGLVL=DEBUG
    # Can be used instead of proxy secret
    # volumes:
    #   - ./mealie_scraper_dc/proxy.txt:/usr/src/app/mealie_scraper/proxy.txt

secrets:
  api_token:
    file: ./api_token.txt
  proxy:
    file: ./proxy.txt
